import { createHash } from 'node:crypto'
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import sharp from 'sharp'

const sourceDir = path.resolve(process.argv[2] ?? '/Users/erlaichuan/Documents/public:/aigc')
const projectRoot = path.resolve(import.meta.dirname, '..')
const outputDir = path.join(projectRoot, 'public/assets/aigc')
const dataFile = path.join(projectRoot, 'src/data/aigc.generated.ts')

const sourceFiles = (await readdir(sourceDir))
  .filter((name) => /^\d+\.(?:jpe?g|png|webp)$/i.test(name))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))

if (sourceFiles.length !== 13) {
  throw new Error(`Expected 13 AIGC images, found ${sourceFiles.length} in ${sourceDir}`)
}

await mkdir(outputDir, { recursive: true })
for (const oldFile of await readdir(outputDir)) {
  if (/^aigc-\d{2}-\d+\.webp$/i.test(oldFile)) await rm(path.join(outputDir, oldFile))
}

const generated = []
for (const [index, fileName] of sourceFiles.entries()) {
  const expected = String(index + 1)
  if (path.parse(fileName).name !== expected) {
    throw new Error(`Expected ${expected}.*, found ${fileName}`)
  }

  const sourceBuffer = await readFile(path.join(sourceDir, fileName))
  const version = createHash('sha1').update(sourceBuffer).digest('hex').slice(0, 10)
  const metadata = await sharp(sourceBuffer).rotate().metadata()
  if (!metadata.width || !metadata.height) throw new Error(`Cannot read dimensions for ${fileName}`)

  const variantWidths = [...new Set([480, 800, 1200]
    .map((width) => Math.min(width, metadata.width)))]
  const variants = []
  for (const width of variantWidths) {
    const id = String(index + 1).padStart(2, '0')
    const outputName = `aigc-${id}-${width}.webp`
    await sharp(sourceBuffer)
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 86, effort: 5 })
      .toFile(path.join(outputDir, outputName))
    variants.push({ width, url: `/assets/aigc/${outputName}?v=${version}` })
  }

  const preferred = variants.find((variant) => variant.width >= 800) ?? variants.at(-1)
  generated.push({
    id: String(index + 1).padStart(2, '0'),
    width: metadata.width,
    height: metadata.height,
    src: preferred.url,
    srcSet: variants.map((variant) => `${variant.url} ${variant.width}w`).join(', '),
  })
}

const output = `// Generated by scripts/import-aigc.mjs. Do not edit by hand.\n` +
  `export type AigcImage = {\n  id: string\n  width: number\n  height: number\n  src: string\n  srcSet: string\n}\n\n` +
  `export const AIGC_IMAGES: AigcImage[] = ${JSON.stringify(generated, null, 2)}\n`

await writeFile(dataFile, output)
console.log(`Imported ${generated.length} AIGC images from ${sourceDir}`)
