import { createHash } from 'node:crypto'
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import sharp from 'sharp'

const sourceDir = path.resolve(process.argv[2] ?? '/Users/erlaichuan/Documents/public:/rating')
const projectRoot = path.resolve(import.meta.dirname, '..')
const outputDir = path.join(projectRoot, 'public/assets/rating')
const dataFile = path.join(projectRoot, 'src/data/rating.generated.ts')
const widths = [480, 800, 1200]

const sourceFiles = (await readdir(sourceDir))
  .filter((name) => /^\d{2}\.(?:jpe?g|png|webp)$/i.test(name))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))

if (sourceFiles.length !== 14) {
  throw new Error(`Expected 14 rating images, found ${sourceFiles.length} in ${sourceDir}`)
}

await mkdir(outputDir, { recursive: true })
for (const oldFile of await readdir(outputDir)) {
  if (/^rating-\d{2}-\d+\.webp$/i.test(oldFile)) {
    await rm(path.join(outputDir, oldFile))
  }
}

const generated = []
for (const [index, fileName] of sourceFiles.entries()) {
  const expected = String(index + 1).padStart(2, '0')
  if (!fileName.startsWith(`${expected}.`)) {
    throw new Error(`Expected ${expected}.*, found ${fileName}`)
  }

  const sourcePath = path.join(sourceDir, fileName)
  const sourceBuffer = await readFile(sourcePath)
  const version = createHash('sha1').update(sourceBuffer).digest('hex').slice(0, 10)
  const metadata = await sharp(sourceBuffer).rotate().metadata()
  if (!metadata.width || !metadata.height) {
    throw new Error(`Cannot read dimensions for ${fileName}`)
  }

  const variants = []
  for (const width of widths) {
    const outputName = `rating-${expected}-${width}.webp`
    await sharp(sourceBuffer)
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 86, effort: 5 })
      .toFile(path.join(outputDir, outputName))
    variants.push(`/assets/rating/${outputName}?v=${version}`)
  }

  generated.push({
    id: expected,
    width: metadata.width,
    height: metadata.height,
    src: variants[1],
    srcSet: variants.map((url, i) => `${url} ${widths[i]}w`).join(', '),
  })
}

const output = `// Generated by scripts/import-rating.mjs. Do not edit by hand.\n` +
  `export type RatingImage = {\n  id: string\n  width: number\n  height: number\n  src: string\n  srcSet: string\n}\n\n` +
  `export const RATING_IMAGES: RatingImage[] = ${JSON.stringify(generated, null, 2)}\n`

await writeFile(dataFile, output)
console.log(`Imported ${generated.length} rating images from ${sourceDir}`)
