// Generated by scripts/import-aigc.mjs. Do not edit by hand.
export type AigcImage = {
  id: string
  width: number
  height: number
  src: string
  srcSet: string
}

export const AIGC_IMAGES: AigcImage[] = [
  {
    "id": "01",
    "width": 480,
    "height": 720,
    "src": "/assets/aigc/aigc-01-480.webp?v=324470ed3b",
    "srcSet": "/assets/aigc/aigc-01-480.webp?v=324470ed3b 480w"
  },
  {
    "id": "02",
    "width": 480,
    "height": 720,
    "src": "/assets/aigc/aigc-02-480.webp?v=52fdcb0d5e",
    "srcSet": "/assets/aigc/aigc-02-480.webp?v=52fdcb0d5e 480w"
  },
  {
    "id": "03",
    "width": 600,
    "height": 900,
    "src": "/assets/aigc/aigc-03-600.webp?v=47d3a011cf",
    "srcSet": "/assets/aigc/aigc-03-480.webp?v=47d3a011cf 480w, /assets/aigc/aigc-03-600.webp?v=47d3a011cf 600w"
  },
  {
    "id": "04",
    "width": 480,
    "height": 720,
    "src": "/assets/aigc/aigc-04-480.webp?v=24f5b83acc",
    "srcSet": "/assets/aigc/aigc-04-480.webp?v=24f5b83acc 480w"
  },
  {
    "id": "05",
    "width": 480,
    "height": 720,
    "src": "/assets/aigc/aigc-05-480.webp?v=8c3f6fd988",
    "srcSet": "/assets/aigc/aigc-05-480.webp?v=8c3f6fd988 480w"
  },
  {
    "id": "06",
    "width": 480,
    "height": 720,
    "src": "/assets/aigc/aigc-06-480.webp?v=9c2b4bf1c1",
    "srcSet": "/assets/aigc/aigc-06-480.webp?v=9c2b4bf1c1 480w"
  },
  {
    "id": "07",
    "width": 480,
    "height": 720,
    "src": "/assets/aigc/aigc-07-480.webp?v=190a97b5f0",
    "srcSet": "/assets/aigc/aigc-07-480.webp?v=190a97b5f0 480w"
  },
  {
    "id": "08",
    "width": 1200,
    "height": 1800,
    "src": "/assets/aigc/aigc-08-800.webp?v=949c57b25c",
    "srcSet": "/assets/aigc/aigc-08-480.webp?v=949c57b25c 480w, /assets/aigc/aigc-08-800.webp?v=949c57b25c 800w, /assets/aigc/aigc-08-1200.webp?v=949c57b25c 1200w"
  },
  {
    "id": "09",
    "width": 3508,
    "height": 4678,
    "src": "/assets/aigc/aigc-09-800.webp?v=f9285a6330",
    "srcSet": "/assets/aigc/aigc-09-480.webp?v=f9285a6330 480w, /assets/aigc/aigc-09-800.webp?v=f9285a6330 800w, /assets/aigc/aigc-09-1200.webp?v=f9285a6330 1200w"
  },
  {
    "id": "10",
    "width": 480,
    "height": 720,
    "src": "/assets/aigc/aigc-10-480.webp?v=5cbe924b91",
    "srcSet": "/assets/aigc/aigc-10-480.webp?v=5cbe924b91 480w"
  },
  {
    "id": "11",
    "width": 480,
    "height": 720,
    "src": "/assets/aigc/aigc-11-480.webp?v=ebed388f64",
    "srcSet": "/assets/aigc/aigc-11-480.webp?v=ebed388f64 480w"
  },
  {
    "id": "12",
    "width": 480,
    "height": 720,
    "src": "/assets/aigc/aigc-12-480.webp?v=2b8cb624ec",
    "srcSet": "/assets/aigc/aigc-12-480.webp?v=2b8cb624ec 480w"
  },
  {
    "id": "13",
    "width": 1200,
    "height": 1600,
    "src": "/assets/aigc/aigc-13-800.webp?v=75f30e846e",
    "srcSet": "/assets/aigc/aigc-13-480.webp?v=75f30e846e 480w, /assets/aigc/aigc-13-800.webp?v=75f30e846e 800w, /assets/aigc/aigc-13-1200.webp?v=75f30e846e 1200w"
  }
]
