/**
 * Generated by scripts/import-project-books.mjs.
 * Do not edit by hand; rerun the importer after changing /work: source images.
 */

export type ProjectBook = {
  id: string
  sourceName: string
  cover: string | null
  pages: readonly string[]
}

export const PROJECT_BOOKS = [
  {
    "id": "project-01",
    "sourceName": "cisheng-zhiwoxin",
    "cover": "project-01-cover",
    "pages": [
      "project-01-page-001",
      "project-01-page-002",
      "project-01-page-003",
      "project-01-page-004",
      "project-01-page-005",
      "project-01-page-006",
      "project-01-page-007",
      "project-01-page-008",
      "project-01-page-009",
      "project-01-page-010",
      "project-01-page-011",
      "project-01-page-012",
      "project-01-page-013",
      "project-01-page-014",
      "project-01-page-015",
      "project-01-page-016"
    ]
  },
  {
    "id": "project-02",
    "sourceName": "nanyang-wangshi",
    "cover": "project-02-cover",
    "pages": [
      "project-02-page-001",
      "project-02-page-002",
      "project-02-page-003",
      "project-02-page-004",
      "project-02-page-005",
      "project-02-page-006",
      "project-02-page-007",
      "project-02-page-008",
      "project-02-page-009",
      "project-02-page-010",
      "project-02-page-011",
      "project-02-page-012"
    ]
  },
  {
    "id": "project-03",
    "sourceName": "lijiangxianziderenjianyanhuo",
    "cover": "project-03-cover",
    "pages": [
      "project-03-page-001",
      "project-03-page-002",
      "project-03-page-003",
      "project-03-page-004",
      "project-03-page-005",
      "project-03-page-006",
      "project-03-page-007",
      "project-03-page-008",
      "project-03-page-009",
      "project-03-page-010"
    ]
  },
  {
    "id": "project-04",
    "sourceName": "tiangangjinhun",
    "cover": "project-04-cover",
    "pages": [
      "project-04-page-001",
      "project-04-page-002",
      "project-04-page-003",
      "project-04-page-004",
      "project-04-page-005",
      "project-04-page-006",
      "project-04-page-007",
      "project-04-page-008",
      "project-04-page-009",
      "project-04-page-010",
      "project-04-page-011",
      "project-04-page-012"
    ]
  },
  {
    "id": "project-05",
    "sourceName": "tongquechunshen",
    "cover": "project-05-cover",
    "pages": [
      "project-05-page-001",
      "project-05-page-002",
      "project-05-page-003",
      "project-05-page-004",
      "project-05-page-005",
      "project-05-page-006",
      "project-05-page-007",
      "project-05-page-008",
      "project-05-page-009",
      "project-05-page-010",
      "project-05-page-011",
      "project-05-page-012"
    ]
  },
  {
    "id": "project-06",
    "sourceName": "sisixiangnian",
    "cover": "project-06-cover",
    "pages": [
      "project-06-page-001",
      "project-06-page-002",
      "project-06-page-003",
      "project-06-page-004",
      "project-06-page-005",
      "project-06-page-006",
      "project-06-page-007",
      "project-06-page-008",
      "project-06-page-009",
      "project-06-page-010",
      "project-06-page-011",
      "project-06-page-012",
      "project-06-page-013",
      "project-06-page-014",
      "project-06-page-015",
      "project-06-page-016",
      "project-06-page-017",
      "project-06-page-018",
      "project-06-page-019",
      "project-06-page-020",
      "project-06-page-021"
    ]
  },
  {
    "id": "project-07",
    "sourceName": "sihouguimitiwotanlianai",
    "cover": "project-07-cover",
    "pages": [
      "project-07-page-001",
      "project-07-page-002",
      "project-07-page-003",
      "project-07-page-004",
      "project-07-page-005",
      "project-07-page-006",
      "project-07-page-007",
      "project-07-page-008",
      "project-07-page-009",
      "project-07-page-010"
    ]
  },
  {
    "id": "project-08",
    "sourceName": "xindongweimian",
    "cover": "project-08-cover",
    "pages": [
      "project-08-page-001",
      "project-08-page-002",
      "project-08-page-003",
      "project-08-page-004",
      "project-08-page-005",
      "project-08-page-006",
      "project-08-page-007",
      "project-08-page-008",
      "project-08-page-009"
    ]
  },
  {
    "id": "project-09",
    "sourceName": "furenmeitiandouzaidanxindiaoma",
    "cover": "project-09-cover",
    "pages": [
      "project-09-page-001",
      "project-09-page-002",
      "project-09-page-003",
      "project-09-page-004",
      "project-09-page-005",
      "project-09-page-006",
      "project-09-page-007",
      "project-09-page-008",
      "project-09-page-009"
    ]
  }
] as const satisfies readonly ProjectBook[]

const PROJECT_BOOK_VERSIONS = {
  "project-01-cover": "c67f09d5",
  "project-01-page-001": "ba9efc56",
  "project-01-page-002": "f131752e",
  "project-01-page-003": "9fe4137e",
  "project-01-page-004": "b3776180",
  "project-01-page-005": "b16f67a8",
  "project-01-page-006": "b77f9134",
  "project-01-page-007": "3537e645",
  "project-01-page-008": "6d3872ec",
  "project-01-page-009": "edf636cc",
  "project-01-page-010": "4c498939",
  "project-01-page-011": "408defbd",
  "project-01-page-012": "2fcf1f72",
  "project-01-page-013": "48e8dbbc",
  "project-01-page-014": "4fa7f7de",
  "project-01-page-015": "ba985455",
  "project-01-page-016": "ce02885c",
  "project-02-cover": "8f1497c3",
  "project-02-page-001": "ce1be39c",
  "project-02-page-002": "476ee400",
  "project-02-page-003": "f066c151",
  "project-02-page-004": "1e795a76",
  "project-02-page-005": "665ac688",
  "project-02-page-006": "661895e9",
  "project-02-page-007": "82d92997",
  "project-02-page-008": "e0cb0ab9",
  "project-02-page-009": "f09881ab",
  "project-02-page-010": "32fbf6cb",
  "project-02-page-011": "d19ab021",
  "project-02-page-012": "eccca145",
  "project-03-cover": "a6b2dd99",
  "project-03-page-001": "dad0daf9",
  "project-03-page-002": "74703399",
  "project-03-page-003": "8d426d67",
  "project-03-page-004": "b758f193",
  "project-03-page-005": "4415082c",
  "project-03-page-006": "797f9844",
  "project-03-page-007": "3b4790c6",
  "project-03-page-008": "f6d9a0ce",
  "project-03-page-009": "7e95f1f0",
  "project-03-page-010": "45e9f04f",
  "project-04-cover": "39259c3d",
  "project-04-page-001": "58e30916",
  "project-04-page-002": "f6cec09e",
  "project-04-page-003": "c0f1628e",
  "project-04-page-004": "53c7011f",
  "project-04-page-005": "0c93ca37",
  "project-04-page-006": "bbdd8770",
  "project-04-page-007": "7dcc82ac",
  "project-04-page-008": "114ef85e",
  "project-04-page-009": "b8854eeb",
  "project-04-page-010": "6bcfd676",
  "project-04-page-011": "d224f6a1",
  "project-04-page-012": "024161b8",
  "project-05-cover": "9da249b3",
  "project-05-page-001": "ed696730",
  "project-05-page-002": "6a873891",
  "project-05-page-003": "c1b2333f",
  "project-05-page-004": "0071b60e",
  "project-05-page-005": "3ea27bc3",
  "project-05-page-006": "91b92a15",
  "project-05-page-007": "b6d30950",
  "project-05-page-008": "47819bad",
  "project-05-page-009": "77a521b0",
  "project-05-page-010": "11d9537b",
  "project-05-page-011": "761afa2f",
  "project-05-page-012": "13019d7e",
  "project-06-cover": "ab997159",
  "project-06-page-001": "082fd0f3",
  "project-06-page-002": "dc7468ae",
  "project-06-page-003": "6018daed",
  "project-06-page-004": "cd0ad908",
  "project-06-page-005": "e56c77fc",
  "project-06-page-006": "aed5256a",
  "project-06-page-007": "605ae215",
  "project-06-page-008": "5b1fc657",
  "project-06-page-009": "02b33357",
  "project-06-page-010": "ff0e9847",
  "project-06-page-011": "ce9430f3",
  "project-06-page-012": "4d991e9d",
  "project-06-page-013": "2fc92629",
  "project-06-page-014": "1423c4dd",
  "project-06-page-015": "d18120cf",
  "project-06-page-016": "9560429e",
  "project-06-page-017": "ed765cce",
  "project-06-page-018": "acde8056",
  "project-06-page-019": "2e7c4bc6",
  "project-06-page-020": "e736a203",
  "project-06-page-021": "da16f788",
  "project-07-cover": "a482a68f",
  "project-07-page-001": "65d21e77",
  "project-07-page-002": "fd5137bb",
  "project-07-page-003": "84236337",
  "project-07-page-004": "8976ea26",
  "project-07-page-005": "759aa919",
  "project-07-page-006": "11ce6113",
  "project-07-page-007": "db5bf2ae",
  "project-07-page-008": "58c38d37",
  "project-07-page-009": "73185690",
  "project-07-page-010": "199de862",
  "project-08-cover": "ea88ad53",
  "project-08-page-001": "31236754",
  "project-08-page-002": "97364ff9",
  "project-08-page-003": "38eec716",
  "project-08-page-004": "4850a4d3",
  "project-08-page-005": "42ff6347",
  "project-08-page-006": "33117fbb",
  "project-08-page-007": "2bf17951",
  "project-08-page-008": "271dc521",
  "project-08-page-009": "62a5bd6f",
  "project-09-cover": "4f16a329",
  "project-09-page-001": "e689e02d",
  "project-09-page-002": "def5ce20",
  "project-09-page-003": "dae3c88d",
  "project-09-page-004": "a652eff8",
  "project-09-page-005": "e349b535",
  "project-09-page-006": "4dfc22fe",
  "project-09-page-007": "f03258fa",
  "project-09-page-008": "403d6926",
  "project-09-page-009": "039a9c01"
} as const

export const projectBookImage = (name: string) => {
  const version = PROJECT_BOOK_VERSIONS[name as keyof typeof PROJECT_BOOK_VERSIONS]
  const query = version ? '?v=' + version : ''
  return {
    src: '/assets/projects/' + name + '-760.webp' + query,
    srcSet:
      '/assets/projects/' + name + '-420.webp' + query + ' 420w, ' +
      '/assets/projects/' + name + '-760.webp' + query + ' 760w',
  }
}
