// Generated by scripts/import-rating.mjs. Do not edit by hand.
export type RatingImage = {
  id: string
  width: number
  height: number
  src: string
  srcSet: string
}

export const RATING_IMAGES: RatingImage[] = [
  {
    "id": "01",
    "width": 1500,
    "height": 2250,
    "src": "/assets/rating/rating-01-800.webp?v=d385d08175",
    "srcSet": "/assets/rating/rating-01-480.webp?v=d385d08175 480w, /assets/rating/rating-01-800.webp?v=d385d08175 800w, /assets/rating/rating-01-1200.webp?v=d385d08175 1200w"
  },
  {
    "id": "02",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-02-800.webp?v=6f621eb8ec",
    "srcSet": "/assets/rating/rating-02-480.webp?v=6f621eb8ec 480w, /assets/rating/rating-02-800.webp?v=6f621eb8ec 800w, /assets/rating/rating-02-1200.webp?v=6f621eb8ec 1200w"
  },
  {
    "id": "03",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-03-800.webp?v=5d532bdb4e",
    "srcSet": "/assets/rating/rating-03-480.webp?v=5d532bdb4e 480w, /assets/rating/rating-03-800.webp?v=5d532bdb4e 800w, /assets/rating/rating-03-1200.webp?v=5d532bdb4e 1200w"
  },
  {
    "id": "04",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-04-800.webp?v=464c0245fc",
    "srcSet": "/assets/rating/rating-04-480.webp?v=464c0245fc 480w, /assets/rating/rating-04-800.webp?v=464c0245fc 800w, /assets/rating/rating-04-1200.webp?v=464c0245fc 1200w"
  },
  {
    "id": "05",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-05-800.webp?v=ec0a3d35ec",
    "srcSet": "/assets/rating/rating-05-480.webp?v=ec0a3d35ec 480w, /assets/rating/rating-05-800.webp?v=ec0a3d35ec 800w, /assets/rating/rating-05-1200.webp?v=ec0a3d35ec 1200w"
  },
  {
    "id": "06",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-06-800.webp?v=3992f726f7",
    "srcSet": "/assets/rating/rating-06-480.webp?v=3992f726f7 480w, /assets/rating/rating-06-800.webp?v=3992f726f7 800w, /assets/rating/rating-06-1200.webp?v=3992f726f7 1200w"
  },
  {
    "id": "07",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-07-800.webp?v=d0a8322811",
    "srcSet": "/assets/rating/rating-07-480.webp?v=d0a8322811 480w, /assets/rating/rating-07-800.webp?v=d0a8322811 800w, /assets/rating/rating-07-1200.webp?v=d0a8322811 1200w"
  },
  {
    "id": "08",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-08-800.webp?v=e77ea75d72",
    "srcSet": "/assets/rating/rating-08-480.webp?v=e77ea75d72 480w, /assets/rating/rating-08-800.webp?v=e77ea75d72 800w, /assets/rating/rating-08-1200.webp?v=e77ea75d72 1200w"
  },
  {
    "id": "09",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-09-800.webp?v=5319ee42ab",
    "srcSet": "/assets/rating/rating-09-480.webp?v=5319ee42ab 480w, /assets/rating/rating-09-800.webp?v=5319ee42ab 800w, /assets/rating/rating-09-1200.webp?v=5319ee42ab 1200w"
  },
  {
    "id": "10",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-10-800.webp?v=4a4c29277c",
    "srcSet": "/assets/rating/rating-10-480.webp?v=4a4c29277c 480w, /assets/rating/rating-10-800.webp?v=4a4c29277c 800w, /assets/rating/rating-10-1200.webp?v=4a4c29277c 1200w"
  },
  {
    "id": "11",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-11-800.webp?v=9d0465d66e",
    "srcSet": "/assets/rating/rating-11-480.webp?v=9d0465d66e 480w, /assets/rating/rating-11-800.webp?v=9d0465d66e 800w, /assets/rating/rating-11-1200.webp?v=9d0465d66e 1200w"
  },
  {
    "id": "12",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-12-800.webp?v=d88d06f93e",
    "srcSet": "/assets/rating/rating-12-480.webp?v=d88d06f93e 480w, /assets/rating/rating-12-800.webp?v=d88d06f93e 800w, /assets/rating/rating-12-1200.webp?v=d88d06f93e 1200w"
  },
  {
    "id": "13",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-13-800.webp?v=a3484e1f24",
    "srcSet": "/assets/rating/rating-13-480.webp?v=a3484e1f24 480w, /assets/rating/rating-13-800.webp?v=a3484e1f24 800w, /assets/rating/rating-13-1200.webp?v=a3484e1f24 1200w"
  },
  {
    "id": "14",
    "width": 1200,
    "height": 1800,
    "src": "/assets/rating/rating-14-800.webp?v=3412dd49f8",
    "srcSet": "/assets/rating/rating-14-480.webp?v=3412dd49f8 480w, /assets/rating/rating-14-800.webp?v=3412dd49f8 800w, /assets/rating/rating-14-1200.webp?v=3412dd49f8 1200w"
  }
]
